aio-libs/aioodbc

aioodbc/cursor.py
tests/test_cursor.py

Fix cursor execute API

---

aioodbc/connection.py
tests/test_connection.py

add post hook.

---

CHANGES.txt
aioodbc/connection.py
tests/test_connection.py
tests/test_cursor.py

Fixes https://github.com/aio-libs/aioodbc/issues/181

Handles echo parameter in cursor properly

---

tests/test_pool.py

Flaky test fixture

---

.github/workflows/python-package.yml
Makefile
aioodbc/__init__.py
aioodbc/connection.py
aioodbc/cursor.py
aioodbc/log.py
aioodbc/pool.py
aioodbc/utils.py
examples/example_complex_queries.py
examples/example_context_managers.py
examples/example_pool.py
examples/example_simple.py
requirements-dev.txt
setup.py
tests/conftest.py
tests/test_connection.py
tests/test_cursor.py
tests/test_pool.py
tests/test_slow.py

Format code with black and isort, enforce formatting on CI.

---

aioodbc/connection.py
requirements-dev.txt

Fix bugbear.

---

docs/conf.py
tests/conftest.py

Apply pyupgrade --py37-plus

---

requirements-dev.txt
setup.py

Bumpy pyodbc dependency to unlock py3.11

---

aioodbc/__init__.py
aioodbc/connection.py
aioodbc/pool.py
tests/conftest.py
tests/test_connection.py
tests/test_pool.py
tests/test_slow.py

Remove usage of explicit loop for new python compatibility.

---

.github/workflows/python-package.yml

Try more pythons.

---

aioodbc/cursor.py
aioodbc/utils.py

Remove compatibility with py3.5

---

.github/dependabot.yml
.github/workflows/python-package.yml
aioodbc/__init__.py
pyproject.toml
requirements-dev.txt
setup.py

Use setuptools_scm to track version.

---

.gitignore
Makefile
aioodbc/__init__.py
aioodbc/utils.py
requirements-dev.txt

Add mypy to the dev dependencies.

---

Makefile
aioodbc/connection.py
aioodbc/pool.py
aioodbc/utils.py

Rework context manager to be similar to aiopg.

---

aioodbc/__init__.py
aioodbc/connection.py
aioodbc/cursor.py
aioodbc/pool.py

Reorder functions to be typing friendly.

---

.github/workflows/python-package.yml
Makefile
aioodbc/__init__.py
aioodbc/pool.py

Apply types on Pool class.

---

aioodbc/pool.py

Correct pool aexit types.

---

aioodbc/connection.py

More typing for connection.

---

aioodbc/cursor.py
tests/test_cursor.py

Add `Cursor.fetchval()` method that calls `pyoodbc.Cursor.fetchval()`
No. This is just an addition of a method.

Add Cursor.fetchval method

---

requirements-dev.txt
setup.py

Bump dependencies for future support py3.12

---

requirements-dev.txt
tests/conftest.py

Remove aiodocker and related fixtures, since they are not used anyway.

---

.github/workflows/python-package.yml
requirements-dev.txt
setup.py
tests/conftest.py

Tonybaloney verify 312

---

CHANGES.txt

Update changes, preare for release.
